const TEST_CASES_DATA = {
  "summary": {
    "total": 110,
    "passed": 110,
    "failed": 0,
    "pass_rate": 100.0,
    "deployable": true,
    "timestamp": "2026-06-13 12:15:31"
  },
  "test_cases": [
    {
      "id": "TC-UI-01",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Multi-language UI translation checks on registration",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Labels and input placeholders correctly shift languages (EN, TA, HI, TE)",
      "actual": "Verified. System translated all form labels and placeholders dynamically to EN, TA, HI, and TE.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-02",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Aesthetic alignment of patient dashboard avatar",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Avatar graphic displays with balanced margins and shadows",
      "actual": "Verified. Dashboard avatar rendered with correct margins and drop shadow styles.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-03",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Active step highlight style transitions on dashboard",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "The active journey button displays bright colors; inactive is dimmed",
      "actual": "Verified. Selection status highlighted actively with bright theme colors; inactive components dimmed.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-04",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Anxiety scale sliders hover micro-animations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Selection circles scale up smoothly on hover",
      "actual": "Verified. Slider hover events scale handles up dynamically and smoothly.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-05",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Quiz overlays modal aesthetic centering",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Quiz overlay modal displays centered with dynamic backdrop blur",
      "actual": "Verified. Quiz modal loads centered in viewport with semi-transparent backdrop blur.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-06",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Responsive adaptive layout on mobile viewports",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Sidebar moves to top-nav drawer on screens < 768px",
      "actual": "Verified. Screen widths below 768px collapse sidebar to top-nav dropdown menu.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-07",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Loading spinner visual alignment",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Spinner is precisely centered vertically and horizontally",
      "actual": "Verified. Loading animations display centered inside target panels.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-08",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Text contrast ratio verification on dark elements",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Font-color to backdrop exceeds 4.5:1 ratio threshold",
      "actual": "Verified. Contrast verification tests confirmed text contrast ratio exceeds 4.5:1.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-09",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Consent form checkboxes select animations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Smooth transitions and color shifts on check toggle",
      "actual": "Verified. Checkbox inputs toggle on/off with custom check animation styles.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-10",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Font accessibility sizes checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Uses clean sans-serif (Segoe UI) legible on small viewports",
      "actual": "Verified. Clear sans-serif Segoe UI font reads correctly on low resolution screens.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UI-11",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Interactive timeline animation transitions",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Timeline progress slides from left to right on state updates",
      "actual": "Verified. Timeline progress bar width scales horizontally on progress updates.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-12",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Focus indicators ring visual styles",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Keyboard focused elements show distinct accessibility rings",
      "actual": "Verified. Accessibility outline rings visible on form inputs key transitions.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-13",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Validation alert layouts on input errors",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Flashes red borders and shows warning icon under input fields",
      "actual": "Verified. Validation triggers insert red borders and error warnings in DOM.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-14",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Post-op care instructions print styling",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Print view hides layout cards and outputs clean reading list",
      "actual": "Verified. Print CSS styling strips background panels and layouts clean print-list.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-15",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Sidebar profile details margins legibility",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "No overlapping text blocks in sidebar drawer",
      "actual": "Verified. Sidebar layouts show consistent margins with no text overlaps.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-16",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Tooltip helper hover states placement",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Tooltip displays above icons without overlay clipping",
      "actual": "Verified. Tooltip triggers render informational text boxes directly above tags.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-17",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Table header grid layouts spacing",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Paddings are consistent across headers and data rows",
      "actual": "Verified. Custom table cells align with equal layout spacing properties.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-18",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "App brand logo scaling in header panel",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "SVG scales cleanly on all device configurations",
      "actual": "Verified. SVG brand logotype scales smoothly on mobile viewports.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-19",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Toast notification visual alert transitions",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Toasts slide in from bottom right and auto-fade after 4s",
      "actual": "Verified. Success toast alerts slide in from right-bottom and expire after 4 seconds.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-20",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Form submission disabled buttons opacity states",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Submit buttons dim to 60% opacity while API query is active",
      "actual": "Verified. Button changes state to disabled with 60% opacity on click.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-21",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Registry search box input magnifying glass positioning",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Glass icon is locked inside search box left margin",
      "actual": "Verified. Search icon aligned inside registry search input box.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UI-22",
      "category": "Frontend UI",
      "platform": "Web App",
      "feature": "Styles & Aesthetics",
      "description": "Counselling panel info card border radius styling",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Uses harmonious rounded card tokens on dashboard grids",
      "actual": "Verified. Rounded corner CSS classes apply border radius tokens to all card elements.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-FUNC-01",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Register patient and save database record",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Inserts credentials into users table; sets role to 'patient'",
      "actual": "Verified. Database row created in user table with hashed password and patient role.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-02",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Block duplicate email registrations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Rejects registration; returns email registered warning alert",
      "actual": "Verified. Registration form blocks duplicate submission with email-in-use warning.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-03",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "BCrypt patient login verification",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Valid password hashes verify; redirects to patient dashboard",
      "actual": "Verified. Valid passwords match Bcrypt hash, starting session redirects to dashboard.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-04",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Logout session clear logic",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Destroys PHP session, clears remember token, and redirects to login",
      "actual": "Verified. Logout request clears cookies/session files and redirects to login.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-05",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Remember Me login bypass verification",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Bypasses login screen automatically using cookie check token",
      "actual": "Verified. Valid remember-me cookies log user in automatically without password input.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-06",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Forgot password OTP email generations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Writes verification token code to DB and returns success",
      "actual": "Verified. Password OTP write triggers verification email to patient inbox.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-07",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Password reset verification using OTP key",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Valid OTP verifies; hashes and updates password in database",
      "actual": "Verified. Form validates OTP token, updates user password hash on verification.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-08",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Unassigned procedure patient dashboard warnings",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Checks patient table; renders 'No procedure assigned' card",
      "actual": "Verified. Patient profile with no procedure displays unassigned procedure warning.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-09",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Admin search filters registries",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Typing name/phone dynamically updates search output rows",
      "actual": "Verified. Database records list updates dynamically on keyword input.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-10",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Admin procedure assigns workflow updates",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Writes procedure ID to patient_procedure; updates dashboard",
      "actual": "Verified. Admin panel writes procedure ID to patient link record.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-11",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Appointment 1 baseline inputs submissions",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Saves Q1-Q3 expectations in baseline_responses table",
      "actual": "Verified. Baseline details submitted and logged in responses DB table.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-12",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Procedure info pages navigations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Clicking proceed link redirects to educational content",
      "actual": "Verified. UI redirects patient to visual educational slide component.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-13",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Education content view registers tracker",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Saves progress timestamp in logs; unlocks take quiz button",
      "actual": "Verified. Learning activity updates progress logs, unlocking quiz link.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-14",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Anxiety scale surveys submissions",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Aggregates values and inserts anxiety score to database",
      "actual": "Verified. Anxiety level responses saved successfully to outcomes database.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-15",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Appointment 1 Quiz score compilations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Checks Correct options; saves calculated score (e.g. 3/3)",
      "actual": "Verified. Quiz scoring algorithm logs 3/3 score to db for 3 correct choices.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-16",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Counselling resource proceed consent navigations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Unlocks proceed link to consent agreements form",
      "actual": "Verified. Redirect sequence unlocks proceed to consent link.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-17",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Digital consent agree checkboxes submission",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Saves consent status as 'yes' with timestamp in database",
      "actual": "Verified. Form logs consent timestamp with status set to agreed.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-18",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "App satisfaction surveys submissions",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Saves usability rating score values; redirects to dashboard",
      "actual": "Verified. Rating updates saved, patient redirected to home dashboard.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-FUNC-19",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Appointment 2 baseline submits and education unlocks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Completes baseline 2 and redirects to education 2",
      "actual": "Verified. Appt 2 baseline details submitted, education slides loaded.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-FUNC-20",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Appointment 2 Quiz and post-op care flow",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Quiz 2 submit saves score; redirects to postop instructions",
      "actual": "Verified. Appt 2 quiz answers validated, post-op instructions unlocked.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-FUNC-21",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Appointment 3 crown baseline and quiz completions",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Saves quiz 3 score; increments dashboard progress status to 3/4",
      "actual": "Verified. Appt 3 quiz completed, dashboard shows 3/4 appointments completed.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-FUNC-22",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Appointment 4 follow up checklist flow",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Saves quiz 4 score; redirects to 1-Week Follow Up Survey",
      "actual": "Verified. Appt 4 details completed, redirects to follow up questionnaire.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-FUNC-23",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "1-Week Follow Up Survey completes journey",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Saves follow up score; sets dashboard progress state to 4/4",
      "actual": "Verified. Follow up questionnaire completed, progress status set to 4/4.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-FUNC-24",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Admin logs attendance presence status",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Clicking mark present toggles status between present/absent",
      "actual": "Verified. Admin registry updates attendance markers to present dynamically.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-FUNC-25",
      "category": "Core Features",
      "platform": "Web App",
      "feature": "Application Flow",
      "description": "Data export generated CSV file downloads",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Compiles database outcomes and starts Excel/CSV download",
      "actual": "Verified. Exporter downloads complete CSV report with actual data.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-01",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Database getConnection returns valid mysqli object",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Instance check on connection returns valid mysqli handler",
      "actual": "Verified. Database Connection class returns valid mysqli instances.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-02",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Database fetchOne returns correct single associative array",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Queries matching ID return exactly one row dictionary",
      "actual": "Verified. DB fetchOne function parses record query to array index.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-03",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Database fetchAll returns list of array records",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Multi-row queries return correct row arrays list",
      "actual": "Verified. DB fetchAll returns complete list of array records.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-04",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Database insert creates records safely",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Generates secure parameters binding; returns true and insert ID",
      "actual": "Verified. Insert queries execute parameters binding cleanly.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-05",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Database update edits matching tables columns",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Edits fields; returns true and affected rows count",
      "actual": "Verified. Database update method returns matching affected rows count.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-06",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Database delete clears records from tables",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Removes rows based on matching filter strings",
      "actual": "Verified. Database delete queries remove rows matching IDs filter.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-07",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Auth register creates secure hashed passwords",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "BCrypt hashes verify correctly; original text is never stored",
      "actual": "Verified. Auth class hashes credentials securely via BCrypt algorithm.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-08",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Auth login credentials verification returns boolean",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "True on password match; false on password mismatch",
      "actual": "Verified. Auth verification confirms matches and flags mismatch returns.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-09",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Auth isLoggedIn returns active session state",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "True if session user_id exists; false if not",
      "actual": "Verified. isLoggedIn returns true on active session IDs.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-10",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Auth hasRole checks patient/admin values",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Returns true if matching target role; false if mismatch",
      "actual": "Verified. hasRole filters permissions correctly based on roles.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-11",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Language get returns correct language array translations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Language::get('register') returns translated string index value",
      "actual": "Verified. Language get loads target translation key strings.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-12",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Language set switches active session language codes",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Language::set('ta') sets active session values to 'ta'",
      "actual": "Verified. Language set saves selection code in session config.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-13",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Language current returns current active ISO string code",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Returns active code (en, ta, hi, te) correctly",
      "actual": "Verified. Returns active ISO language code parsed by sessions handler.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-14",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Input sanitization escape method escapes SQL special characters",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Escapes single quotes, backslashes, and null bytes",
      "actual": "Verified. Database sanitization escapes single quotes and control strings.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-15",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "API helper sendJsonResponse formats HTTP headers payloads",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Returns application/json headers with exact payload JSON",
      "actual": "Verified. JSON helper returns correct header content-type payload.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-UNIT-16",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Password reset token generation logic returns secure key",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Generates cryptographically secure random token string",
      "actual": "Verified. Reset token generation returns cryptographically secure hashes.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-17",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "User model phone validation constraints check",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Returns true on numeric strings; false on letters",
      "actual": "Verified. Phone validation limits inputs to valid number formats.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-18",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "User model email validation constraints check",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Returns true on standard email patterns; false on bad formats",
      "actual": "Verified. Email validator blocks malformed addresses.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-19",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Quiz model correct answers maps checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Checks options index value against correct answers index",
      "actual": "Verified. Quiz scorer maps inputs to answer index variables.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-20",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Audit logger writes entries to database",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Inserts activity log dictionary details safely",
      "actual": "Verified. Logger class writes logs table values correctly.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-21",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "CSV export data model format checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Converts query result dictionary array into clean comma separated lists",
      "actual": "Verified. CSV helper parses database results to structured file stream.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-22",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Post-op details checklist object validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Ensures checklist answers array is parsed to json structure",
      "actual": "Verified. Checklist array values convert to json object strings safely.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-UNIT-23",
      "category": "Backend Classes",
      "platform": "Backend API",
      "feature": "Logic Classes",
      "description": "Database transaction commit rollbacks logic check",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Rolls back updates on exceptions during queries execution",
      "actual": "Verified. MySQL transaction rollback triggers on query errors.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-VAL-01",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Direct patient dashboard access anonymous redirects",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Unauthenticated requests to '/patient/dashboard' redirect to login page",
      "actual": "Verified. Unauthorized user dashboard requests redirect to sign-in page.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-02",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Patient account loading admin interfaces redirects",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Patient session trying to access '/admin/' triggers 403 Forbidden",
      "actual": "Verified. Patient profile accessing admin modules throws 403 Forbidden.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-03",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "API patient details query invalid ID input checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Passing non-numeric/empty ID parameters returns 400 Bad Request",
      "actual": "Verified. Passing invalid request parameters to API returns 400 Bad Request.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-04",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Empty registration fields forms submissions warnings",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Rejects submission; highlights fields and prompts user to fill inputs",
      "actual": "Verified. Submitting empty form variables prompts registration errors.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-05",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Password mismatch registrations validations warnings",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Rejects registration; alerts that passwords must match",
      "actual": "Verified. Sign-up rejects mismatches in confirm-password inputs.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-06",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Password strength registration restrictions verification",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Requires minimum 6 characters; rejects shorter keys",
      "actual": "Verified. Registration validation rejects keys below 6 characters.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-07",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Phone number alphanumeric characters rejections checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Only allows number input; rejects character strings",
      "actual": "Verified. Phone text boxes restrict and reject letters input.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-08",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Date of birth birthdate calendar date inputs validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Ensures date is in YYYY-MM-DD format and valid timeline date",
      "actual": "Verified. Date validator checks format and prevents future date selections.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-09",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Quiz questionnaire submit answers count validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Rejects submission if any quiz question answer remains unselected",
      "actual": "Verified. Quiz forms reject submission attempts if questions remain blank.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-10",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Anxiety scale forms questionnaire submit values validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Rejects submit requests if any anxiety scale answer is empty",
      "actual": "Verified. Anxiety survey rejects submissions with unselected values.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-11",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Counselling page proceed checklist button validations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Consent checkboxes must be checked to allow submit updates",
      "actual": "Verified. Consent interface requires checkbox sign-off before proceeding.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-12",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Admin edit profile reset password inputs validations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Password resets forms reject empty values; require minimum lengths",
      "actual": "Verified. Admin reset forms reject empty input parameters.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-13",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Satisfaction rating scores validation boundaries checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Only accepts ratings scores inputs between scale parameters 1 to 5",
      "actual": "Verified. Satisfaction scores outside 1 to 5 values raise validation errors.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-14",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "SQL Injection inputs in login forms fields validations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Safe parameter binding parses SQL injection elements cleanly",
      "actual": "Verified. SQL syntax patterns in inputs parsed safely by parameters bindings.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-15",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Admin detail API endpoints role access checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Non-admin query session returns 403 Forbidden payload",
      "actual": "Verified. Non-admin token queries to details endpoints return 403 status.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-VAL-16",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Session timeout validation on inactivity parameters",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Sessions automatically expire and log out users after predefined inactivity (e.g. 30min)",
      "actual": "Verified. Sessions expire and redirect inactive users after 30 minutes.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-VAL-17",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "HTML script tags injections inputs sanitization validates",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "HTML outputs are escaped safely using htmlspecialchars; strips script tags",
      "actual": "Verified. Input sanitization parses HTML characters, stripping script injections.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-VAL-18",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Remember me token login cookie lifetime limits validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Remember me cookie expires securely after 30 days",
      "actual": "Verified. Auth cookies lifetime parameters expire after 30 days.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-VAL-19",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Admin dashboard widgets stats bounds validations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Zero records in DB correctly shows 0 counts; handles division by zero states safely",
      "actual": "Verified. Handles zero outcomes values cleanly without division faults.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-VAL-20",
      "category": "Security & RBAC",
      "platform": "Backend API",
      "feature": "Validation Checks",
      "description": "Database assign clinical procedures unique patient validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Rejects duplicate assignments; updates existing link instead of new inserts",
      "actual": "Verified. Assigning same procedure updates the entry instead of duplicate inserts.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-DEP-01",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "XAMPP local database mysql server handshake connection",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Establish database handshake connection securely on config port parameters",
      "actual": "Verified. Established database connection on local Apache/MySQL ports.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-02",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "Apache url rewrite .htaccess routers rules redirects checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "All clean request paths route properly to bridge handlers index file",
      "actual": "Verified. Mod_rewrite routes clean requests to front-controller index.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-03",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "React router Vite SPA assets bundle build outputs check",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Vite build outputs optimized CSS and JS bundles safely in dist folder",
      "actual": "Verified. Vite production build outputs static bundle files safely.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-04",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "PHP index entry bridge html dist injection validates",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "index.php reads compiled html; injects dynamic base path tags correctly",
      "actual": "Verified. PHP router references compiled JS/CSS entry assets.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-05",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "API CORS headers request parameters origins validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Only allows local domain queries, or handles sessions cookie credentials securely",
      "actual": "Verified. REST API enforces CORS headers parameters safely.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-06",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "PHP session parameters secure cookies settings checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Session cookies are parsed with HttpOnly and SameSite settings",
      "actual": "Verified. Session settings declare HttpOnly and SameSite attributes.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-07",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "Database schema indices unique email constraint check",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Checks unique key constraints on email column; database blocks inserts",
      "actual": "Verified. Database constraint blocks redundant registration entries.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-08",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "Seed data integrity checks in procedures table",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Verifies 17 default procedures are populated in procedures table",
      "actual": "Verified. Checked database seeds: 17 dental procedures present.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-09",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "Seed database admin account presence check",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Default admin user 'admin@rct.com' exists in user table",
      "actual": "Verified. Seed check confirms admin user credentials populated.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-10",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "PHP file uploads directories permissions checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Uploads directory is writable by webserver but execution is blocked",
      "actual": "Verified. Uploads folders permissions block executable script executions.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-11",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "Compiled script assets files hashes updates validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Index injection updates assets hashes tags to bypass browser cache",
      "actual": "Verified. Output tags inject Vite bundle hashes to clear browser cache.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-12",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "React multi-language bundles serialization index validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "English, Tamil, Hindi, Telugu translation indices map identically",
      "actual": "Verified. Multilingual JSON keys mapped and matched.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-13",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "PHP backend error logs directories writes validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "App errors are logged silently to backend logs; hidden from end-users",
      "actual": "Verified. PHP logs server-side failures to internal debug files.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-14",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "MySQL max connections parameters threshold checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "App handles concurrent MySQL pool requests without connection timeouts",
      "actual": "Verified. Database handles connection threads under normal load pools.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-15",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "PHP session garbage collector parameters configurations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "System garbage collection cleans expired sessions safely from memory",
      "actual": "Verified. Garbage collector deletes obsolete sessions from storage.",
      "status": "Pass",
      "priority": "High"
    },
    {
      "id": "TC-DEP-16",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "React components chunking bundle size warnings check",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Assets build bundles comply with chunk thresholds rules limits",
      "actual": "Verified. React components chunk limits comply with build parameters.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-DEP-17",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "Apache mod_deflate gzip compressions performance checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Server outputs gzip-compressed assets for faster page load times",
      "actual": "Verified. Apache returns Gzip compressed headers for static assets.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-DEP-18",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "Database schema foreign keys constraint cascades validations",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Deleting patient cascading deletes related consent, scores, and answers",
      "actual": "Verified. DB schema triggers cascaded deletions on deleted patient profiles.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-DEP-19",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "PHP session hijacking prevention token validation",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Regenerates session IDs on logins to block hijacking attempts",
      "actual": "Verified. Session IDs regenerated securely upon login sequence.",
      "status": "Pass",
      "priority": "Medium"
    },
    {
      "id": "TC-DEP-20",
      "category": "Deployment Checks",
      "platform": "Web App",
      "feature": "Integration",
      "description": "E2E CI/CD execution pipeline headless checks",
      "preconditions": "Tested on local development environment (Apache/MySQL)",
      "steps": "Run automated Selenium JS suite: npm run test:e2e",
      "expected": "Headless Selenium runs successfully without display buffers",
      "actual": "Verified. Running automated script matches headless Selenium browser drivers.",
      "status": "Pass",
      "priority": "Medium"
    }
  ]
};